def convert_log_to_html(log_file, output_html):
    with open(log_file, "r") as file:
        lines = file.readlines()

    html_content = """
    <html>
    <head>
        <style>
            /* Global styles */
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background-color: #f9f9f9;
                margin: 30px;
                color: #333;
            }

            h2 {
                color: #2c3e50;
                font-size: 28px;
                margin-bottom: 20px;
                text-align: center;
                text-transform: uppercase;
                letter-spacing: 1px;
            }

            /* Table styling */
            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 30px;
                box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
                background-color: #fff;
            }

            th, td {
                padding: 12px;
                text-align: left;
            }

            th {
                background-color: #3498db;
                color: white;
                font-size: 16px;
                font-weight: bold;
            }

            td {
                font-size: 14px;
                border-bottom: 1px solid #f0f0f0;
            }

            /* Hover effects */
            tr:nth-child(even) {
                background-color: #f4f7fa;
            }

            tr:hover {
                background-color: #ecf0f1;
                cursor: pointer;
            }

            /* Add a subtle effect to the table */
            table, th, td {
                border: 1px solid #e0e0e0;
            }

            /* Responsive design */
            @media (max-width: 768px) {
                table {
                    width: 100%;
                    font-size: 12px;
                }
            }

            /* Footer for the page */
            footer {
                text-align: center;
                margin-top: 40px;
                font-size: 14px;
                color: #7f8c8d;
            }

            footer a {
                color: #3498db;
                text-decoration: none;
            }
        </style>
    </head>
    <body>
        <h2>Test Execution Report</h2>
        <table>
            <tr><th>Timestamp</th><th>Log Level</th><th>Message</th></tr>
    """

    for line in lines:
        parts = line.strip().split(" - ")
        if len(parts) >= 3:
            html_content += f"<tr><td>{parts[0]}</td><td>{parts[1]}</td><td>{parts[2]}</td></tr>"

    html_content += """
        </table>
        <footer>
            <p>Generated by the Log Converter Tool | <a href="#">View more reports</a></p>
        </footer>
    </body>
    </html>
    """

    with open(output_html, "w") as file:
        file.write(html_content)

    print(f"HTML Report Generated: {output_html}")
