name: Python API Automation Tests

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the operating system (Ubuntu in this case)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m venv .venv
        . .venv/bin/activate
        pip install -r requirements.txt  # Install the dependencies

    - name: Run tests
      run: |
        . .venv/bin/activate
        pytest --maxfail=1 --disable-warnings -v --log-file=logs/test_log.log  # Run tests and output logs to a file

    - name: Convert log to HTML
      run: |
        python utils/html_report.py logs/test_log.log logs/test_log.html  # Convert the log file to HTML using html_report.py

    - name: Upload log files as artifacts
      if: always()  # Upload logs even if tests fail
      uses: actions/upload-artifact@v4  # Updated to the latest versio
